defaults:
  - default.yaml

watch_model:
  _target_: src.callbacks.wandb_callbacks.WatchModel
  log: "all"
  log_freq: 100

#upload_ckpts_as_artifact:
#  _target_: src.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
#  upload_best_only: True

text_generation:
  _target_: src.callbacks.wandb_callbacks.TextGenerationCallback
  data_dir: ${datamodule.processed_data_dir}
  limit: 100  # use `-1` for no limit
