_target_: src.datamodules.prompts.WritingPromptsDataModule

data_dir: ${data_dir}/prompts  # data_dir is specified in config.yaml
batch_size: 32
percentage: 100  # percentage of dataset to load
shuffle: True  # `True` shuffles dataset every epoch
padding: 'max_length'  # padding strategy (check `Tokenizers` documentation)
truncation: True  # truncation strategy (check `Tokenizers` documentation)
max_story_length: 1024  # max story length in tokens (enforced)
max_summary_length: 65  # max summary length in tokens (enforced)
load_dataset_from_file: True
train_files: 'train.csv'
val_files: 'valid.csv'
test_files: 'test.csv'
processed_data_dir: '${data_dir}/proc_prompts'
