_target_: src.datamodules.prompts_sent.WritingPromptsOneSentenceDataModule

data_dir: ${data_dir}/.writingPrompts  # data_dir is specified in config.yaml
batch_size: 16
percentage: 100  # percentage of dataset to load
shuffle: True  # `True` shuffles dataset every epoch
padding: 'max_length'  # padding strategy (check `Tokenizers` documentation)
truncation: True  # truncation strategy (check `Tokenizers` documentation)
max_story_length: 422  # max story length in tokens (enforced)
max_summary_length: 130  # max summary length in tokens (enforced)
load_dataset_from_file: True
train_files: [ 'train.wp_source', 'train.wp_target' ]
val_files: [ 'valid.wp_source', 'valid.wp_target' ]
test_files: [ 'test.wp_source', 'test.wp_target' ]
processed_data_dir: '${data_dir}/.processed_writingprompts'
