_target_: src.datamodules.roc.ROCStoriesDataModule

data_dir: ${data_dir}/roc  # data_dir is specified in config.yaml
batch_size: 32
percentage: 100  # percentage of dataset to load
shuffle: True  # `True` shuffles dataset every epoch
padding: 'max_length'  # padding strategy (check `Tokenizers` documentation)
truncation: True  # truncation strategy (check `Tokenizers` documentation)
max_story_length: 60  # max story length in tokens
max_summary_length: 20  # max summary length in tokens
load_dataset_from_file: True
train_files: 'roc_stories_sent_concat.csv'
processed_data_dir: '${data_dir}/proc_roc_stories_sent'
