_target_: src.models.compressor_model.CompressorModel

name: 'Compressor'  # used for experiment logging
model_name_or_path: 'facebook/bart-base'
learning_rate: 5e-5
max_generation_length: ${datamodule.max_summary_length}  # max length to use when generating summaries